require "test_helper"

class ConvertTest < Minitest::Spec
  it "what" do
    FileUtils.rm(Dir.glob("test/ruby/operation/*.rb"))

    Trailblazer::Core.convert_operation_test("test/ruby/activity_test.rb", target: "test/ruby/operation/activity_test.rb", source_gem: "trailblazer-activity")

    assert_equal File.read("test/ruby/operation/activity_test.rb"), %(# THIS FILE IS AUTOGENERATED FROM trailblazer-activity/test/ruby/activity_test.rb
require "test_helper"

module X
  class DocsActivityTest < Minitest::Spec
    it "basic activity" do
      Memo = Struct.new(:options) do
        def save
          true
        end
      end

      #:memo-create
      module Memo::Operation
        class Create < Trailblazer::Operation
          step :validate
          #~body
          step :save
          left :handle_errors
          step :notify
          #~meths
          include T.def_steps(:validate, :save, :handle_errors, :notify)

          #:save
          def save(ctx, params:, **)
            memo = Memo.new(params[:memo])
            memo.save

            ctx[:model] = memo # you can write to the {ctx}.
          end
          #:save end

          def notify(ctx, **)
            true
          end

          #~body end
          def validate(ctx, params:, **) # home-made validation
            params.key?(:memo) &&
            params[:memo].key?(:text) &&
            params[:memo][:text].size > 9
            # return value matters!
          end
          #~meths end
        end
      end
      #:memo-create end

      #:memo-call
      result = Memo::Operation::Create.(
        params: {memo: {text: "Do not forget!"}}
      )

      result.success? # => true
      puts signal.to_h[:semantic] #=> :success
      #:memo-call end

      #:memo-call-model
      result = Memo::Operation::Create.(
        params: {memo: {text: "Do not forget!"}}
      )

      #~ctx_to_result
      puts result[:model] #=> #<Memo id: 1 text: "Do not forget!">
      #:memo-call-model end
      #~ctx_to_result end

      assert_equal result.terminus.inspect, %(#<Trailblazer::Operation::End semantic=:success>)
      assert_equal result.inspect, %({:params=>{:memo=>{:text=>\\\"Do not forget!\\\"}}, :model=>#<struct X::DocsActivityTest::Memo options={:text=>\\\"Do not forget!\\\"}>})

      model = ctx[:model]

      assert_invoke Memo::Operation::Create, seq: "[]", params: {memo: {text: "Do not forget!"}}, expected_ctx_variables: {model: model}
      assert_invoke Memo::Operation::Create, seq: "[:handle_errors]", params: {}, terminus: :failure

      variable = Trailblazer::Operation
    end

    #~keep
    Trailblazer::Activity::Railway
    Trailblazer::Activity::Signal
    Trailblazer::Activity::FastTrack
    #~keep end

    class Update < Trailblazer::Operation
    end
  end
end
)
  end
end
